# See https://ezcv.readthedocs.io for documentation
name: Arshi Chariyekkara
theme: dimension
resume: true
email: arshi.chariyekkara.uts.edu.au
social: 
  linkedin: arshi-c-a005a023a?trk=public_profile_browsemap&original_referer=https%3A%2F%2Fwww.google.com%2F
biography: hello! this is an example of how to use ezcv to create an awesome page on Github 